baseURL = "https://brisberg.dev/"
languageCode = "en-us"
title = "Brandon Risberg"
theme = "minimal"

[params]
    author = "Brandon Risberg"
    githubUsername = "brisberg"
    description = "Personal blog and website"
    copyright = "&copy; 2020 All rights reserved. Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal)."
    # accent = "#E34E47"
    # showBorder = true
    # backgroundColor = "white"
    font = "Quicksand" # should match the name on Google Fonts!

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "https://blog.brisberg.dev"
    name = "Blog"
    weight = 2

[[menu.main]]
    url = "https://wiki.brisberg.dev"
    name = "Wiki"
    weight = 3

[[menu.main]]
    url = "/apps/"
    name = "Apps"
    weight = 4

[[menu.main]]
    url = "/cv.pdf"
    name = "CV"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/
[[menu.icon]]
    url = "https://twitter.com/brisberg"
    name = "twitter"
    weight = 1

[[menu.icon]]
    url = "https://github.com/brisberg"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.instagram.com/brisberg"
    name = "instagram"
    weight = 3

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCEKqrUfr_FMKIO9XSJS4vDw"
    name = "youtube"
    weight = 4
