name: Publish Wiki

on:
  push:
    paths:
      # Trigger only when wiki directory or workflow changes
      - 'wiki/**'
      - .github/workflows/publish-wiki.yml
    branches:
      # And only on main branch
      - main

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v5
      env:
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ github.event.pusher.email }}
        GH_NAME: ${{ github.event.pusher.name }}
